### ISSUE TITLE
Installing requirement.txt error

### ISSUE THREAD

**Issue by energy-trader** [AncillaryServicesAcquisitionModel/ASAM#2]
Hi ,

It seems I'm having an issue with creating a virtual environment with the requirements.txt file, it appears some of the packages are outdated, and it seems when updating the necessary packages I receive a conflict error between packages. Would it be possible for myself to update all the entire requirements file, and would the environment execute then?

**Comment by AncillaryServicesAcquisitionModel** [comment]
Hi @energy-trader ,
ASAM has now been updated to latest Python packages. In particulary the PyPSA update to v. 0.25.1 and Pandas led to quite some changes. 
Please try again if you can use the requirements file.

Best regards,
Samuel
